export enum CommentTypes {
  GET_LATEST = 'COMMENT_GET_LATEST',
  POST_AS_CHARACTER = 'COMMENT_AS_CHARACTER',
  POST_AS_CORPORATION = 'COMMENT_AS_CORPORATION',
  POST_AS_ALLIANCE = 'COMMENT_AS_ALLIANCE',
}
