export enum PostTypes {
  GET_LATEST = 'GET_LATEST',
  GET_CHARACTER_WALL = 'GET_CHARACTER_WALL',
  GET_CORPORATION_WALL = 'GET_CORPORATION_WALL',
  GET_ALLIANCE_WALL = 'GET_ALLIANCE_WALL',
  POST_AS_CHARACTER = 'POST_AS_CHARACTER',
  POST_AS_CORPORATION = 'POST_AS_CORPORATION',
  POST_AS_ALLIANCE = 'POST_AS_ALLIANCE',
}
