export enum PostTypes {
  GET_LATEST = 'POST_GET_LATEST',
  GET_HASHTAG = 'POST_GET_HASHTAG',
  GET_CHARACTER_WALL = 'POST_GET_CHARACTER_WALL',
  GET_CORPORATION_WALL = 'POST_GET_CORPORATION_WALL',
  GET_ALLIANCE_WALL = 'POST_GET_ALLIANCE_WALL',
  POST_AS_CHARACTER = 'POST_AS_CHARACTER',
  POST_AS_CORPORATION = 'POST_AS_CORPORATION',
  POST_AS_ALLIANCE = 'POST_AS_ALLIANCE',
}
