export enum PostTypes {
  GET_LATEST = 'GET_LATEST',
  GET_CHARACTER_WALL = 'GET_CHARACTER_WALL',
  GET_CORPORATION_WALL = 'GET_CORPORATION_WALL',
  GET_ALLIANCE_WALL = 'GET_ALLIANCE_WALL',
  SUBMIT_POST = 'SUBMIT_POST'
}
